### ISSUE TITLE
What is blue ring, what is red dot, what is scale?

### ISSUE THREAD

**Issue by dneise** [MaxNoe/find_dark_spot#1]
In changeset b43dec2 (currently installed on gui) 

There is no scale in the map, so one does not immediately get, what one is looking at.

The red dot, shows the pointing of FACT. The size of the red dot does not mean anything. 
The FoV is not shown, especially, it is *not* the case, that the size of the red dot *is* the FoV of FACT.

The blue dashed circle is the minimum zenith angle, allowed for a ratescan position. So in default configuration it is the 10° ring. 

Maybe one can include some of this info, into the plot.

**Comment by MaxNoe** [comment]
Yes, i'm planning to do that. I changed the plotting library, because it is so much nicer besides the fact that i did not find a simple way to plot the fov.

**Comment by MaxNoe** [comment]
Done in 2b9d09867675 and 8c54585c14
![new_find_dark_spot](https://cloud.githubusercontent.com/assets/5488440/8788077/34c5c59c-2f38-11e5-909b-021e658ea613.png)
